### ISSUE TITLE
support for non-encrypted data in same secret

### ISSUE THREAD

**Issue by tooptoop4** [h3poteto/kms-secrets#409]
would be great to support another section for unencrypted data, ie plaintext username that is associated with a password

ie
```
apiVersion: secret.h3poteto.dev/v1beta1
kind: KMSSecret
metadata:
  name: test1sec
  namespace: testing
spec:
  data:
    USER: my_db_username
  encryptedData:
    PASSWORD: AQICAHh2iCEGE2e6vdC+w6dQ4hRIyahEPE...
```
