### ISSUE TITLE
create same secret in multiple namespaces with just one yaml?

### ISSUE THREAD

**Issue by tooptoop4** [h3poteto/kms-secrets#410]
define the KMS value once, but have the secret created into 2 different namespaces

ie
```
apiVersion: secret.h3poteto.dev/v1beta1
kind: KMSSecret
metadata:
  name: test1sec
  namespace: "name1, name2"
spec:
  encryptedData:
    PASSWORD: AQICAHh2iCEGE2e6vdC+w6dQ4hRIyahEPE...
```
